Update online-setup

diff --git a/ChocholousekPicons/online-setup b/ChocholousekPicons/online-setup
--- a/ChocholousekPicons/online-setup
+++ b/ChocholousekPicons/online-setup
@@ -3,14 +3,16 @@
 ##########################################################################################
 
 show_man_page() {
-    echo "===== Chocholousek Picons - online installation script ====="
-    echo "USAGE:"
+    echo '===== Chocholousek Picons - online installation script ====='
+    echo 'USAGE:'
     echo '      wget -qO- --no-check-certificate "https://github.com/s3n0/e2plugins/blob/master/ChocholousekPicons/online-setup?raw=true" | bash -s <ARGUMENT>'
-    echo "ARGUMENT:"
-    echo "      install ....... install the plugin (with the Enigma2 fast restart)"
-    echo "      uninstall ..... uninstall the plugin (with the Enigma2 fast restart)"
-    echo "      del-config .... delete the plugin configuration only & exit the script"
-    echo "      del-plugin .... delete the plugin directory only & exit the script"
+    echo '   OR:'
+    echo '      curl -LJso- "https://github.com/s3n0/e2plugins/blob/master/ChocholousekPicons/online-setup?raw=true" | bash -s <ARGUMENT>'
+    echo 'ARGUMENT:'
+    echo '      install ....... install the plugin (with the Enigma2 fast restart)'
+    echo '      uninstall ..... uninstall the plugin (with the Enigma2 fast restart)'
+    echo '      del-config .... delete the plugin configuration only & exit the script'
+    echo '      del-plugin .... delete the plugin directory only & exit the script'
 }
 
 e2_stop() {
@@ -45,21 +47,24 @@ plugin_dir_del() {
 ##########################################################################################
 
 [ -z "$1" ] && { show_man_page; echo -e "\nError ! No argument found !"; exit 1; }
-
 PKGNAME="enigma2-plugin-extensions-chocholousek-picons"
+# wget --help | grep -qim1 "busybox" && PROXYARG="--proxy off" || PROXYARG="--no-proxy"
+curl --help > /dev/null 2>&1 && DOWNLOADER="curl -L -J -s -o" || DOWNLOADER="wget --no-check-certificate -q -O"
+
+##########################################################################################
 
 case "$1" in
     install)
         # retrieve the latest version number (from internet)
-    ### VER="$(wget -qO- --no-check-certificate https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/src/version.txt)"
-    ### VER="$(wget -qO- --no-check-certificate https://raw.githubusercontent.com/s3n0/e2plugins/master/ChocholousekPicons/src/version.txt)"
-        VER="$(wget -qO- --no-check-certificate https://github.com/s3n0/e2plugins/blob/master/ChocholousekPicons/src/version.txt?raw=true)"
+    ### VER=`$DOWNLOADER - https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/src/version.txt`
+    ### VER=`$DOWNLOADER - https://raw.githubusercontent.com/s3n0/e2plugins/master/ChocholousekPicons/src/version.txt`
+        VER=`$DOWNLOADER - https://github.com/s3n0/e2plugins/blob/master/ChocholousekPicons/src/version.txt?raw=true`
         [ -z "$VER" ] && { echo "Error ! The online version was not recognized !"; exit 1; }
         # download the plugin installation package from internet
         FNAME="${PKGNAME}_${VER}_all.$([ -d /etc/dpkg ] && echo -n 'deb' || echo -n 'ipk')"
-    ### wget -qO "/tmp/${FNAME}" --no-check-certificate "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/released_build/${FNAME}" || { echo "Error ! File download failed !"; exit 1; }
-    ### wget -qO "/tmp/${FNAME}" --no-check-certificate "https://raw.githubusercontent.com/s3n0/e2plugins/master/ChocholousekPicons/released_build/${FNAME}" || { echo "Error ! File download failed !"; exit 1; }
-        wget -qO "/tmp/${FNAME}" --no-check-certificate "https://github.com/s3n0/e2plugins/blob/master/ChocholousekPicons/released_build/${FNAME}?raw=true" || { echo "Error ! File download failed !"; exit 1; }
+    ### $DOWNLOADER "/tmp/${FNAME}" "https://github.com/s3n0/e2plugins/raw/master/ChocholousekPicons/released_build/${FNAME}" || { echo "Error ! File download failed !"; exit 1; }
+    ### $DOWNLOADER "/tmp/${FNAME}" "https://raw.githubusercontent.com/s3n0/e2plugins/master/ChocholousekPicons/released_build/${FNAME}" || { echo "Error ! File download failed !"; exit 1; }
+        $DOWNLOADER "/tmp/${FNAME}" "https://github.com/s3n0/e2plugins/blob/master/ChocholousekPicons/released_build/${FNAME}?raw=true" || { echo "Error ! File download failed !"; exit 1; }
         # re-install
         if [ -d /etc/dpkg ]; then
             dpkg -r $PKGNAME                # dpkg -r "${FNAME%%_*}"
